name: Publish Pages

on:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Cache Node modules
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Setup GitHub Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v5
        id: setup

      # Step 5: Install dependencies and build the app
      - name: Build Pages
        run: |
          npm install
          npm run build
        env:
          VITE_BASE_URL: "${{steps.setup.outputs.base_url}}"

      # Step 6: Upload build artifacts to Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      # Step 7: Deploy to GitHub Pages
        environment:
          name: github-pages
        uses: actions/deploy-pages@v4